#!/usr/bin/env python3
"""Rebuild _scripts/ml/posteriors.json from priors + git history.

Usage
-----
    # Recompute posteriors and write posteriors.json
    python _scripts/ml/update_posteriors.py

    # Show predictions (no write) — handy for debugging
    python _scripts/ml/update_posteriors.py --show

    # Show prediction for a single project (incl. expected calendar dates)
    python _scripts/ml/update_posteriors.py --project YOUR_PROJECT_FOLDER_NAME

    # Print extracted observations only
    python _scripts/ml/update_posteriors.py --observations

The cron entry in _scripts/cron/setup_launchd.py runs the no-arg form daily.

Expected .env:
    VAULT_ROOT=/absolute/path/to/vault
"""

from __future__ import annotations

import argparse
import json
import logging
import re
import sys
from datetime import date, timedelta
from pathlib import Path
from typing import Optional

from extract_history import (
    Observation,
    PHASE_SHORT,
    PHASES_ORDER,
    collapse_role,
    extract_observations,
    parse_role,
    parse_status,
)
from posterior import cell_summary

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
)
logger = logging.getLogger("update_posteriors")


ROLES = ("lead", "not_lead")
PHASES_SHORT = ("dc", "dr", "ir")


# ---------------------------------------------------------------------------
# Vault root resolution (mirrors archive_published.py)
# ---------------------------------------------------------------------------


def load_vault_root() -> Path:
    search_dirs = [Path.cwd(), Path(__file__).resolve().parent.parent.parent]
    for d in search_dirs:
        env_path = d / ".env"
        if env_path.exists():
            for line in env_path.read_text().splitlines():
                line = line.strip()
                if line.startswith("VAULT_ROOT="):
                    val = line.split("=", 1)[1].strip().strip("\"'")
                    return Path(val).resolve()
    return Path(__file__).resolve().parent.parent.parent


# ---------------------------------------------------------------------------
# Build posteriors.json
# ---------------------------------------------------------------------------


def group_observations(obs: list[Observation]) -> dict[str, dict[str, list[int]]]:
    grouped: dict[str, dict[str, list[int]]] = {
        r: {p: [] for p in PHASES_SHORT} for r in ROLES
    }
    for o in obs:
        if o.role in grouped and o.phase in grouped[o.role]:
            grouped[o.role][o.phase].append(o.duration_days)
    return grouped


def build_posteriors(priors: dict, observations: list[Observation]) -> dict:
    grouped = group_observations(observations)
    kappa_0 = priors.get("_nig_strength", {}).get("kappa_0", 2.0)
    a_0 = priors.get("_nig_strength", {}).get("a_0", 3.0)

    out: dict = {
        "_doc": (
            "Posterior predictive summary per (role, phase). "
            "Generated by _scripts/ml/update_posteriors.py from priors.json + git log. "
            "DO NOT EDIT BY HAND."
        ),
        "_units": "calendar days",
        "_generated": date.today().isoformat(),
        "_nig_strength": {"kappa_0": kappa_0, "a_0": a_0},
    }
    for role in ROLES:
        out[role] = {}
        for phase in PHASES_SHORT:
            cell_prior = priors[role][phase]
            durations = grouped[role][phase]
            out[role][phase] = {
                **cell_summary(cell_prior, durations, kappa_0=kappa_0, a_0=a_0),
                "observations": durations,
            }
    return out


def load_priors(vault_root: Path) -> dict:
    path = vault_root / "_scripts" / "ml" / "priors.json"
    return json.loads(path.read_text(encoding="utf-8"))


def write_posteriors(vault_root: Path, posteriors: dict) -> Path:
    path = vault_root / "_scripts" / "ml" / "posteriors.json"
    path.write_text(json.dumps(posteriors, indent=2) + "\n", encoding="utf-8")
    return path


# ---------------------------------------------------------------------------
# Per-project prediction (for --project mode)
# ---------------------------------------------------------------------------


def find_project_file(vault_root: Path, code: str) -> Optional[Path]:
    for sub in ("01_PROJECTS", "99_ARCHIVE"):
        cand = vault_root / sub / code / "_project.md"
        if cand.exists():
            return cand
    return None


def show_for_project(vault_root: Path, code: str, posteriors: dict) -> None:
    pf = find_project_file(vault_root, code)
    if pf is None:
        logger.error("Project not found: %s", code)
        sys.exit(1)
    text = pf.read_text(encoding="utf-8")
    role = collapse_role(parse_role(text))
    status = parse_status(text)
    if role is None or status not in PHASES_ORDER:
        logger.error("Cannot determine role/status for %s (role=%s status=%s)", code, role, status)
        sys.exit(1)

    cell = posteriors[role]
    print(f"# Prediction for {code}")
    print(f"role: {role}    current status: {status}")
    print()
    today = date.today()
    cursor = today
    for phase in PHASES_ORDER[:-1]:
        short = PHASE_SHORT[phase]
        c = cell[short]
        p10, p50, p90 = c["p10_days"], c["p50_days"], c["p90_days"]
        idx_phase = PHASES_ORDER.index(phase)
        idx_status = PHASES_ORDER.index(status)
        if idx_phase < idx_status:
            tag = "DONE"
            label = f"{phase:<18s}  {tag}"
            print(label)
            continue
        if idx_phase == idx_status:
            tag = "ACTIVE"
        else:
            tag = "FUTURE"
        end_p50 = cursor + timedelta(days=p50)
        end_p10 = cursor + timedelta(days=p10)
        end_p90 = cursor + timedelta(days=p90)
        label = (
            f"{phase:<18s}  {tag:<6s}  start {cursor}  "
            f"end p50={end_p50}  [p10={end_p10}, p90={end_p90}]  "
            f"({p10}/{p50}/{p90} days, n={c['n']})"
        )
        print(label)
        cursor = end_p50


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------


def main() -> int:
    parser = argparse.ArgumentParser(description="Rebuild Bayesian phase posteriors.")
    parser.add_argument("--show", action="store_true", help="Print posteriors without writing")
    parser.add_argument("--observations", action="store_true", help="Print extracted observations and exit")
    parser.add_argument("--project", type=str, help="Show prediction for one project (e.g. 2026_POLYGALA_REV)")
    args = parser.parse_args()

    vault_root = load_vault_root()
    logger.info("Vault root: %s", vault_root)

    observations = extract_observations(vault_root)
    logger.info("Extracted %d phase observations from git", len(observations))

    if args.observations:
        for o in observations:
            print(f"{o.project_code:<32s}  {o.role:<8s}  {o.phase}  {o.duration_days} days")
        return 0

    priors = load_priors(vault_root)
    posteriors = build_posteriors(priors, observations)

    if args.show or args.project:
        if args.project:
            show_for_project(vault_root, args.project, posteriors)
            return 0
        print(json.dumps(posteriors, indent=2))
        return 0

    out_path = write_posteriors(vault_root, posteriors)
    logger.info("Wrote %s", out_path)
    summary_lines = []
    for role in ROLES:
        for ph in PHASES_SHORT:
            c = posteriors[role][ph]
            summary_lines.append(
                f"  {role:<8s} {ph}  n={c['n']:<3d}  "
                f"p10={c['p10_days']}  p50={c['p50_days']}  p90={c['p90_days']}"
            )
    logger.info("Posterior predictive summary:\n%s", "\n".join(summary_lines))
    return 0


if __name__ == "__main__":
    sys.exit(main())
